@startuml
class cs211.project.controllers.components.MyEventCard {
- Label eventDate
- ImageView eventImage
- Label eventLocation
- Label eventTitle
- Button eventToggleStatus
- Button orderNumber
- Label participantEvent
- String pathEventImage
- boolean statusEvent
- HashMap<String,Object> data
- MyEventController myEventController
- Datasource<EventCollection> datasourceEvent
- Datasource<TeamCollection> datasourceTeam
- Datasource<TeamMemberCollection> datasourceTeamMember
- Datasource<JoinEventCollection> datasourceJoinEvent
+ void initialize()
+ void goToListTeam()
+ void goToEditEvent()
+ void goToParticipant()
+ void goToActivityEvent()
+ void onHandleDeleteEvent()
+ void onHandleEventStatus()
+ String getEventDate()
+ String getEventImage()
+ String getEventLocation()
+ String getEventTitle()
+ String getOrderNumber()
+ String getParticipantEvent()
+ HashMap<String,Object> getData()
+ void setMyEventController(MyEventController)
+ void setEventDate(String)
+ void setEventImage(String)
+ void setEventLocation(String)
+ void setEventTitle(String)
+ void setOrderNumber(String)
+ void setParticipantEvent(String)
+ void setStatusEvent(boolean)
+ void setData(HashMap<String,Object>)
}
class cs211.project.controllers.components.RightChatLayoutController {
- Text myMessage
- Label timestamp
+ String getMyMessage()
+ String getTimestamp()
+ void setMyMessage(String)
+ void setTimestamp(String)
}
class cs211.project.controllers.components.EventCard {
- String eventId
- Label eventDate
- Rectangle eventImage
- String imagePath
- Label eventLocation
- Text eventName
- Label eventParticipant
- HashMap<String,Object> data
- int currentParticipant
- void initialize()
~ void onHandleGoToEventDetail(MouseEvent)
+ String getEventId()
+ String getEventDate()
+ String getEventImage()
+ String getEventLocation()
+ String getEventName()
+ String getEventParticipant()
+ int getCurrentParticipant()
+ void setCurrentParticipant(int)
+ void setEventId(String)
+ void setEventDate(String)
+ void setEventImage(String)
+ void setEventLocation(String)
+ void setEventName(String)
+ void setEventParticipant(String)
+ void setData(HashMap<String,Object>)
}
class cs211.project.controllers.components.JoinTeamCard {
- UUID teamId
- UUID userId
- Button joinTeamButton
- Label teamParticipant
- Label teamName
- Label dateLabel
- HashMap<String,Object> data
- Datasource<TeamMemberCollection> teamMemberDatasource
- Datasource<TeamCollection> teamDatasource
- JoinTeamController joinTeamController
- void initialize()
- boolean teamIsFull()
+ void checkTeamIsFull()
~ void onHandleJoinTeam(ActionEvent)
+ void isJoinedTeam()
+ String getTeamParticipant()
+ String getTeamName()
+ String getTeamId()
+ String getUserId()
+ void setTeamParticipant(String)
+ void setTeamName(String)
+ void setTeamId(String)
+ void setUserId(String)
+ void setJoinTeamController(JoinTeamController)
+ void setJoinTeamButton(boolean,String)
+ void setDate(String,String)
}
class cs211.project.controllers.components.WhiteEventCard {
- String eventId
- Label eventDate
- Rectangle eventImage
- String imagePath
- Label eventLocation
- Text eventName
- Label eventParticipant
- HashMap<String,Object> data
- int currentParticipant
- void initialize()
~ void onHandleGoToEventDetail(MouseEvent)
+ String getEventId()
+ String getEventDate()
+ String getEventImage()
+ String getEventLocation()
+ String getEventName()
+ String getEventParticipant()
+ int getCurrentParticipant()
+ void setCurrentParticipant(int)
+ void setEventDate(String)
+ void setEventImage(String)
+ void setEventLocation(String)
+ void setEventName(String)
+ void setEventParticipant(String)
+ void setData(HashMap<String,Object>)
}
class cs211.project.controllers.components.MyTeamCardController {
- UUID teamId
- UUID userId
- UUID eventId
- Label applicants
- Label teamApplicants
- ImageView eventImage
- Label eventName
- MyTeamController myTeamController
- Button order
- Label startDate
- Label teamName
- Label eventLocation
- Button teamDetailButton
- Button leaveTeamButton
- Datasource<TeamMemberCollection> datasourceTeamMember
+ void setActivityIsEnd()
+ void setParentController(MyTeamController)
+ void setTeamApplicants(String)
+ void setTeamId(String)
+ void setUserId(String)
+ void setEventId(String)
+ void setApplicants(String)
+ void setEventImage(String)
+ void setEventName(String)
+ void setEventLocation(String)
+ void setOrder(String)
+ void setStartDate(String)
+ void setTeamName(String)
+ String getTeamId()
+ String getUserId()
+ String getApplicants()
+ String getEventId()
+ String getEventImage()
+ String getEventName()
+ String getEventLocation()
+ String getOrder()
+ String getStartDate()
+ String getTeamName()
+ String getTeamApplicants()
~ void onHandleGoToTeamManagement(ActionEvent)
~ void onHandleLeaveTeam(ActionEvent)
}
class cs211.project.controllers.components.ProfileImageController {
- Circle profileImage
- String imagePath
+ void setProfileImage(String)
+ String getImagePath()
}
class cs211.project.controllers.components.ListTeamPreview {
- Circle headTeamImageCircle
- Label titleTeamLabel
- String pathHeadTeamImageCircle
+ String getHeadTeamImageCircle()
+ String getTitleTeamLabel()
+ void setHeadTeamImageCircle(String)
+ void setTitleTeamLabel(String)
+ void setPathHeadTeamImageCircle(String)
}
class cs211.project.controllers.components.TeamMemberCard {
- Circle image
- UUID userId
- UUID teamId
- ImageView dropdown
- Label name
- Label role
- Pane menuDropdown
- VBox dropdownVBox
- Pane border
- Button changeRoleButton
- Button deleteTeamMemberButton
- TeamManagementController teamManagementController
- Boolean showMenuDropdown
- Datasource<TeamCollection> teamDatasource
- Datasource<TeamMemberCollection> teamMemberDatasource
- Boolean isLeader
- void initialize()
~ void onHandleMenuDropdownClick(MouseEvent)
~ void onHandleChangeRole(ActionEvent)
~ void onHandleDeleteTeamMember(ActionEvent)
+ String getImage()
+ String getName()
+ String getRole()
+ String getUserId()
+ String getTeamId()
+ void setUserId(String)
+ void setTeamId(String)
+ void setImage(String)
+ void setIsLeader(Boolean)
+ void setDropdownButtonVisible(Boolean)
+ void setName(String)
+ void setRole(String)
+ void setParentController(TeamManagementController)
+ void setChangeRoleButtonVisible(Boolean)
}
class cs211.project.controllers.components.ListTeamCard {
- Circle headTeamImageCircle
- Label headTeamLabel
- Button orderNumber
- Label teamLabel
- String pathHeadTeamImage
- HashMap<String,Object> data
- Datasource<TeamCollection> datasourceTeam
- TeamCollection teamList
- ListTeamController teamController
+ void initialize()
+ void getGoToSettingTeam()
+ void goToEditTeam()
+ void onHandleDeleteTeam()
+ String getHeadTeamImage()
+ String getHeadTeamLabel()
+ String getOrderNumber()
+ String getTeamLabel()
+ HashMap<String,Object> getData()
+ void setHeadTeamImage(String)
+ void setHeadTeamLabel(String)
+ void setOrderNumber(String)
+ void setTeamLabel(String)
+ void setData(HashMap<String,Object>)
+ void setTeamController(ListTeamController)
}
class cs211.project.controllers.components.LeftChatLayoutController {
- Circle senderImage
- Text senderMessage
- Label senderName
- Label timestamp
+ String getSenderMessage()
+ String getSenderName()
+ String getTimestamp()
+ void setSenderName(String)
+ void setSenderMessage(String)
+ void setSenderImage(String)
+ void setTimestamp(String)
}
@enduml