@startuml
class cs211.project.models.Chat {
- UUID id
- UUID userId
- UUID activityId
- String message
- UUID teamId
- String timestamp
+ void setSenderUserId(String)
+ void setMessage(String)
+ void setTimestamp(String)
+ void setActivityId(String)
+ String getSenderUserId()
+ String getMessage()
+ String getTimestamp()
+ String getId()
+ String getTeamId()
+ String getActivityId()
+ HashMap<String,String> toHashMap()
}
class cs211.project.models.TeamMember {
- UUID id
- UUID userId
- UUID teamId
+ String getId()
+ String getUserId()
+ String getTeamId()
+ void setId(String)
+ void setUserId(String)
+ void setTeamId(String)
+ HashMap<String,String> toHashMap()
}
class cs211.project.models.collections.TeamMemberCollection {
- ArrayList<TeamMember> teamMembers
+ void setTeamMembers(ArrayList<TeamMember>)
+ void addTeamMember(TeamMember)
+ ArrayList<TeamMember> getTeamMembers()
+ TeamMember findTeamMemberById(String)
}
class cs211.project.models.User {
- UUID id
- String avatar
- String username
- String password
- String role
- String lastLogin
- String createdAt
+ String getId()
+ void setId(String)
+ String getAvatar()
+ void setAvatar(String)
+ String getUsername()
+ void setUsername(String)
+ String getPassword()
+ void setPassword(String)
+ String getRole()
+ void setRole(String)
+ String getLastLogin()
+ void setLastLogin(String)
+ String getCreatedAt()
+ void setCreatedAt(String)
+ HashMap<String,String> toHashMap()
}
class cs211.project.models.Person {
- String firstName
- String lastName
- String fullName
+ String getFirstName()
+ void setFirstName(String)
+ String getLastName()
+ void setLastName(String)
+ String getFullName()
}
class cs211.project.models.Team {
- UUID id
- String name
- UUID eventId
- UUID leaderId
- String maxMember
- String startDate
- String endDate
- String startTime
- String endTime
+ String getId()
+ String getName()
+ String getEventId()
+ String getLeaderId()
+ String getMaxMember()
+ String getStartDate()
+ String getEndDate()
+ String getStartTime()
+ String getEndTime()
+ void setId(String)
+ void setName(String)
+ void setEventId(String)
+ void setLeaderId(String)
+ void setMaxMember(String)
+ void setStartDate(String)
+ void setEndDate(String)
+ void setStartTime(String)
+ void setEndTime(String)
+ HashMap<String,String> toHashMap()
}
class cs211.project.models.collections.AnswerCollection {
- ArrayList<Answer> answers
+ void addAnswer(Answer)
+ ArrayList<Answer> getAnswers()
}
class cs211.project.models.collections.ChatCollection {
- ArrayList<Chat> chats
+ void addNewChat(Chat)
+ ArrayList<Chat> getChats()
}
class cs211.project.models.Activity {
- UUID id
- String name
- String detail
- String startDate
- String startTime
- String endDate
- String endTime
- String dateTimeStart
- String dateTimeEnd
- Boolean status
- String order
+ String getId()
+ String getName()
+ String getDetail()
+ String getStartDate()
+ String getStartTime()
+ String getEndDate()
+ String getEndTime()
+ void setId(String)
+ void setName(String)
+ void setDetail(String)
+ void setStartDate(String)
+ void setStartTime(String)
+ void setEndDate(String)
+ void setEndTime(String)
+ void setDateTimeStart()
+ void setDateTimeEnd()
+ void setStatus(Boolean)
+ Boolean getStatus()
+ String getDateTimeStart()
+ String getDateTimeEnd()
}
class cs211.project.models.JoinEvent {
- UUID id
- String eventId
- String userId
- String joinTime
- String status
+ String getId()
+ String getEventId()
+ String getUserId()
+ String getJoinTime()
+ String getStatus()
+ void setId(String)
+ void setEventId(String)
+ void setUserId(String)
+ void setJoinTime(String)
+ void setStatus(String)
+ HashMap<String,String> toHashMap()
}
class cs211.project.models.collections.EventCollection {
- ArrayList<Event> events
+ ArrayList<Event> getEvents()
+ void setEvents(ArrayList<Event>)
+ void addEvent(Event)
+ ArrayList<Event> filterByUserId(String)
+ Event findEventById(String)
+ ArrayList<Event> getRandomEvent(int)
+ ArrayList<Event> getPopularEvent()
+ ArrayList<Event> getClosestEvents()
+ ArrayList<Event> getLatestEvents()
+ ArrayList<Event> sortByBeforeEndDate()
+ ArrayList<Event> sortByComparator(Comparator<Event>)
}
class cs211.project.models.collections.TeamActivityCollection {
+ void addNewActivity(TeamActivity)
+ ArrayList<TeamActivity> getActivities()
}
class cs211.project.models.EventActivity {
- UUID eventId
+ String getEventId()
+ void setEventId(String)
+ HashMap<String,String> toHashMap()
}
class cs211.project.models.Answer {
- UUID id
- UUID userId
- String answer
- UUID questionId
- String timestamp
+ String getAnswer()
+ void setAnswer(String)
+ UUID getQuestionId()
+ HashMap<String,String> toHashMap()
}
class cs211.project.models.Event {
- UUID id
- UUID userId
- String name
- String detail
- String location
- String openDate
- String openTime
- String closeDate
- String closeTime
- String startDate
- String startTime
- String endDate
- String endTime
- int maxParticipant
- String image
- boolean status
- String progressStatus
- int participantCount
- LocalDateTime createAt
+ void updateEventStatus()
+ String getStatus()
+ String getId()
+ String getUserId()
+ String getName()
+ String getDetail()
+ String getLocation()
+ String getOpenDate()
+ String getOpenTime()
+ String getCloseDate()
+ String getCloseTime()
+ String getStartDate()
+ String getStartTime()
+ String getEndDate()
+ String getEndTime()
+ int getMaxParticipant()
+ int getParticipantCount()
+ String getImage()
+ boolean isStatus()
+ LocalDateTime getCreateAt()
+ void setUserId(String)
+ void setName(String)
+ void setDetail(String)
+ void setLocation(String)
+ void setOpenDate(String)
+ void setOpenTime(String)
+ void setCloseDate(String)
+ void setCloseTime(String)
+ void setStartDate(String)
+ void setStartTime(String)
+ void setEndDate(String)
+ void setEndTime(String)
+ void setParticipantCount(int)
+ void setMaxParticipant(int)
+ void setPathImagePreview(String)
+ void setStatus(boolean)
+ void setCreateAt(LocalDateTime)
+ HashMap<String,String> toHashMap()
+ String toString()
}
class cs211.project.models.TeamActivity {
- UUID teamId
+ String getTeamId()
+ void setTeamId(String)
+ HashMap<String,String> toHashMap()
}
class cs211.project.models.collections.TeamCollection {
- ArrayList<Team> teams
+ void addTeam(Team)
+ ArrayList<Team> getTeams()
+ void isNameExist(String)
+ void isNameExits(String,String)
+ ArrayList<Team> findTeamByEventId(String)
}
class cs211.project.models.collections.JoinEventCollection {
- ArrayList<JoinEvent> joinEvents
+ ArrayList<JoinEvent> getJoinEvents()
+ void setJoinEvents(ArrayList<JoinEvent>)
+ void addJoinEvent(JoinEvent)
+ ArrayList<JoinEvent> filterByEventId(String)
+ List<String> getEventIdsByUserId(UUID)
}
class cs211.project.models.collections.ActivityCollection {
- ArrayList<T> activities
+ void addNewActivity(T)
+ ArrayList<T> getActivities()
}
class cs211.project.models.collections.UserCollection {
- List<User> users
+ boolean addUser(User)
+ User findUserByUsername(String)
+ User findUserById(String)
+ List<User> findUsersByRole(String)
+ boolean deleteUserById(String)
+ List<User> getAllUsers()
+ void loadUsersFromHashMaps(List<HashMap<String,String>>)
}
class cs211.project.models.collections.EventActivityCollection {
+ void addNewActivity(EventActivity)
+ ArrayList<EventActivity> getActivities()
}


cs211.project.models.Person <|-- cs211.project.models.User
cs211.project.models.collections.ActivityCollection <|-- cs211.project.models.collections.TeamActivityCollection
cs211.project.models.Activity <|-- cs211.project.models.EventActivity
cs211.project.models.Activity <|-- cs211.project.models.TeamActivity
cs211.project.models.collections.ActivityCollection <|-- cs211.project.models.collections.EventActivityCollection
@enduml